---
# Import Library

---

In [1]:
# Processing and Displying Data in DataFrame form.
import pandas as pd

# Calculate Data.
import numpy as np

# Spliting Data into Train and Test
from sklearn.model_selection import train_test_split

# handling Outlier.
# from feature_engine.outliers import Winsorizer

# Scaling Data. (Numeric - Skew)
# from sklearn.preprocessing import MinMaxScaler

# Encode Data. (Categorical - Nominal)
# from sklearn.preprocessing import OneHotEncoder

# Colleration Check each column.
# import phik

# Machine Learning Model.
# from sklearn.linear_model import LogisticRegression
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import RandomForestClassifier

# Calculate, compare, visualize Predict Score.
# from sklearn.metrics import recall_score, confusion_matrix, ConfusionMatrixDisplay

# Model Saving.
# import pickle

# Ignoring Warning from Python.
import warnings
warnings.filterwarnings("ignore")

---
# Data Loading

---

In [2]:
# Using file from cleaned Folder outside .ipynb path file
Data = pd.read_csv('../data/cleaned/order_agg_modeling_v0_1.csv', index_col=0)
Backup_data = Data.copy()

In [3]:
# to Shown all column.
pd.options.display.max_columns = None

# top 5 Data Sample.
Data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items,total_order_value,total_freight,avg_item_price,payment_type,total_payment_value,max_installments,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,is_canceled
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,29.99,8.72,29.99,voucher,38.71,1.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,118.70,22.76,118.70,boleto,141.46,1.0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,159.90,19.22,159.90,credit_card,179.12,3.0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,45.00,27.20,45.00,credit_card,72.20,1.0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,19.90,8.72,19.90,credit_card,28.62,1.0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,0

---
# Feature Engineering

---

---
## Duplicated Check

---

In [4]:
print(f"Duplicated Data  : {Data.duplicated().sum()}")
print(f"Total Data : {Data.shape[0]}")

Duplicated Data  : 0
Total Data : 98832

Based on the duplicate check, no duplicated records were found in the dataset.

---

---
## Missing value Check

---

In [5]:
Data.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1174
order_delivered_customer_date    2356
order_estimated_delivery_date       0
total_items                       172
total_order_value                 172
total_freight                     172
avg_item_price                    172
payment_type                        1
total_payment_value                 1
max_installments                    1
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
is_canceled                         0
dtype: int64

Based on the Missing Value check, there are some columns that need to be handled.

---

---
## Missing Value Handling

---

In [6]:
Data_Processed = Data.drop(columns=['order_approved_at'
                        ,'order_delivered_carrier_date'
                        ,'order_delivered_customer_date'
                        ,'order_estimated_delivery_date']
                ,axis=1 )

TODO   
[need finalize] Reasoning :   
Since the objective of the model is to predict the cancellation rate before the transaction is approved, the approval date column and all subsequent activity date columns will be dropped.

---

In [7]:
Missing_Data = Data_Processed[Data_Processed['payment_type'].isnull()].index
Data_Processed.loc[Missing_Data]

,order_id,customer_id,order_status,order_purchase_timestamp,total_items,total_order_value,total_freight,avg_item_price,payment_type,total_payment_value,max_installments,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,is_canceled
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,3.0,134.97,8.49,44.99,NaN,NaN,NaN,830d5b7aaa3b6f1e9ad63703bec97d23,14600,sao joaquim da barra,SP,0

In [8]:
Data_Processed = Data_Processed.dropna(subset=['payment_type','max_installments','total_payment_value'],axis=0)

TODO   
[Need Finalize] Reasoning :   
The missing values in the `payment_type`, `total_payment_value`, and `max_installments` columns occur in the same row and appear independent of other columns. Because only one record is affected, the row will be removed.

---

In [9]:
Data_Processed['total_items'] = Data_Processed['total_items'].fillna(1)
Data_Processed['total_order_value'] = Data_Processed['total_order_value'].fillna(Data_Processed['total_payment_value'])
Data_Processed['total_freight'] = Data_Processed['total_freight'].fillna(0)
Data_Processed['avg_item_price'] = Data_Processed['avg_item_price'].fillna(Data_Processed['total_payment_value'])

TODO   
[need finalize]Reasoning :   
Missing values in `total_items` are imputed with `1` under the assumption that `each order must contain at least one item`. Since `an order cannot exist without any item`.

for `total_order_value` and `avg_item_price` are imputed using total_payment_value, with total_items are inputed as 1, the `total_order_value` and `avg_item_price` are equivalent to the total amount paid.

for `total_freight` are imputed with `0` as default because min value for `total_freight` is `0` that indicate as `free shipping`

---

In [10]:
Data_Processed.isnull().sum()

order_id                    0
customer_id                 0
order_status                0
order_purchase_timestamp    0
total_items                 0
total_order_value           0
total_freight               0
avg_item_price              0
payment_type                0
total_payment_value         0
max_installments            0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
is_canceled                 0
dtype: int64

TODO   
[need finalize]Reasoning :   
Based on the Missing value check after handling, no missing value records were found in the dataset.

---

---
## Split column X & y

---

In [11]:
# Excluding column that like primary key, candidate primary key and looks like Target column
X = Data_Processed.drop(columns=['customer_id','order_id','customer_unique_id','order_status','is_canceled'],axis=1)

# using is_canceled column as predict target 
y = Data_Processed.is_canceled

In [12]:
X.head()

,order_purchase_timestamp,total_items,total_order_value,total_freight,avg_item_price,payment_type,total_payment_value,max_installments,customer_zip_code_prefix,customer_city,customer_state
0,2017-10-02 10:56:33,1.0,29.99,8.72,29.99,voucher,38.71,1.0,3149,sao paulo,SP
1,2018-07-24 20:41:37,1.0,118.70,22.76,118.70,boleto,141.46,1.0,47813,barreiras,BA
2,2018-08-08 08:38:49,1.0,159.90,19.22,159.90,credit_card,179.12,3.0,75265,vianopolis,GO
3,2017-11-18 19:28:06,1.0,45.00,27.20,45.00,credit_card,72.20,1.0,59296,sao goncalo do amarante,RN
4,2018-02-13 21:18:39,1.0,19.90,8.72,19.90,credit_card,28.62,1.0,9195,santo andre,SP

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98831 entries, 0 to 99440
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_purchase_timestamp  98831 non-null  object
 1   total_items               98831 non-null  float64
 2   total_order_value         98831 non-null  float64
 3   total_freight             98831 non-null  float64
 4   avg_item_price            98831 non-null  float64
 5   payment_type              98831 non-null  object
 6   total_payment_value       98831 non-null  float64
 7   max_installments          98831 non-null  float64
 8   customer_zip_code_prefix  98831 non-null  int64
 9   customer_city             98831 non-null  object
 10  customer_state            98831 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 9.0+ MB

In [14]:
num_col = ['total_items','total_order_value','total_freight','avg_item_price', 'total_payment_value']

cat_col = ['payment_type','max_installments','customer_zip_code_prefix','customer_city','customer_state']

date_col = ['order_purchase_timestamp']

---
## Cardinality Check

---

In [15]:
for i in X[cat_col]:
    print(f'Jumlah unique value dari kolom {i} : {X[i].nunique()}')
    print(f'Unique value dari kolom {i} : {X[i].unique()}')
    print('')

Jumlah unique value dari kolom payment_type : 5
Unique value dari kolom payment_type : ['voucher' 'boleto' 'credit_card' 'debit_card' 'not_defined']

Jumlah unique value dari kolom max_installments : 24
Unique value dari kolom max_installments : [ 1.  3.  6. 10.  4.  2.  8.  9.  7.  5. 13. 12. 15. 14. 21. 18. 24. 17.
 11. 20. 23. 16. 22.  0.]

Jumlah unique value dari kolom customer_zip_code_prefix : 14977
Unique value dari kolom customer_zip_code_prefix : [ 3149 47813 75265 ... 83870  5127 45920]

Jumlah unique value dari kolom customer_city : 4111
Unique value dari kolom customer_city : ['sao paulo' 'barreiras' 'vianopolis' ... 'messias targino'
 'campo do tenente' 'nova vicosa']

Jumlah unique value dari kolom customer_state : 27
Unique value dari kolom customer_state : ['SP' 'BA' 'GO' 'RN' 'PR' 'RS' 'RJ' 'MG' 'SC' 'RR' 'PE' 'TO' 'CE' 'DF'
 'SE' 'MT' 'PB' 'PA' 'RO' 'ES' 'AP' 'MS' 'MA' 'PI' 'AL' 'AC' 'AM']

Based on the Cardinality Check result above, `max_installments`, `customer_zip_code_prefix`, `customer_city`, and `customer_state` are categorized as high-cardinality features and will require appropriate handling.

---

---
## Cardinality handling

---

In [16]:
X['installment_bin'] = pd.cut(
    X['max_installments']
    ,bins=[0, 6, 12, 18, 24]
    ,labels=['very_short','short','medium','long']
    ,include_lowest=True
)

In [17]:
X['installment_bin'].unique()

['very_short', 'short', 'medium', 'long']
Categories (4, object): ['very_short' < 'short' < 'medium' < 'long']